#cross validation
source ~/.bashrc;singularity exec         --bind /scratchc/nrlab/wang04/         --bind ~         --bind /home/nrlab         --bind /home/nrlab/wang04/ulyses/         --bind /scratchc/nrlab/wang04/ulyses         --bind /scratchc/nrlab/wang04/ulyses_results_iteration         /scratchc/nrlab/wang04/docker/tensorflow_gpu_cuda.sif python /home/nrlab/wang04/ulyses/models_logistic_regression/LR_cv.py --input_csv /scratchc/nrlab/wang04/ulyses_results_iteration/iteration_3_merge_below_3/lr_model/lr10/0-0.03_pairwise/lr_input.feat.cnv.tf.0-0.03_pairwise.csv
source ~/.bashrc;singularity exec         --bind /scratchc/nrlab/wang04/         --bind ~         --bind /home/nrlab         --bind /home/nrlab/wang04/ulyses/         --bind /scratchc/nrlab/wang04/ulyses         --bind /scratchc/nrlab/wang04/ulyses_results_iteration         /scratchc/nrlab/wang04/docker/tensorflow_gpu_cuda.sif python /home/nrlab/wang04/ulyses/models_logistic_regression/LR_cv.py --input_csv /scratchc/nrlab/wang04/ulyses_results_iteration/iteration_3_merge_below_3/lr_model/lr10/0.03-0.1_pairwise/lr_input.feat.cnv.tf.0.03-0.1_pairwise.csv
source ~/.bashrc;singularity exec         --bind /scratchc/nrlab/wang04/         --bind ~         --bind /home/nrlab         --bind /home/nrlab/wang04/ulyses/         --bind /scratchc/nrlab/wang04/ulyses         --bind /scratchc/nrlab/wang04/ulyses_results_iteration         /scratchc/nrlab/wang04/docker/tensorflow_gpu_cuda.sif python /home/nrlab/wang04/ulyses/models_logistic_regression/LR_cv.py --input_csv /scratchc/nrlab/wang04/ulyses_results_iteration/iteration_3_merge_below_3/lr_model/lr10/0.1-1_pairwise/lr_input.feat.cnv.tf.0.1-1_pairwise.csv
source ~/.bashrc;singularity exec         --bind /scratchc/nrlab/wang04/         --bind ~         --bind /home/nrlab         --bind /home/nrlab/wang04/ulyses/         --bind /scratchc/nrlab/wang04/ulyses         --bind /scratchc/nrlab/wang04/ulyses_results_iteration         /scratchc/nrlab/wang04/docker/tensorflow_gpu_cuda.sif python /home/nrlab/wang04/ulyses/models_logistic_regression/LR_cv.py --input_csv /scratchc/nrlab/wang04/ulyses_results_iteration/iteration_3_merge_below_3/lr_model/lr10/all/lr_input.feat.cnv.tf.all.csv 



#ind test

source ~/.bashrc;singularity exec         --bind /scratchc/nrlab/wang04/         --bind ~         --bind /home/nrlab         --bind /home/nrlab/wang04/ulyses/         --bind /scratchc/nrlab/wang04/ulyses         --bind /scratchc/nrlab/wang04/ulyses_results_iteration    /scratchc/nrlab/wang04/docker/tensorflow_gpu_cuda.sif python     /home/nrlab/wang04/ulyses/models_logistic_regression/LR_train_and_test_on_exam_data.py --input_csv /scratchc/nrlab/wang04/ulyses_results_iteration/iteration_3_merge_below_3/lr_model/lr10/0-0.03_pairwise/lr_input.feat.cnv.tf.0-0.03_pairwise.csv
source ~/.bashrc;singularity exec         --bind /scratchc/nrlab/wang04/         --bind ~         --bind /home/nrlab         --bind /home/nrlab/wang04/ulyses/         --bind /scratchc/nrlab/wang04/ulyses         --bind /scratchc/nrlab/wang04/ulyses_results_iteration    /scratchc/nrlab/wang04/docker/tensorflow_gpu_cuda.sif python    /home/nrlab/wang04/ulyses/models_logistic_regression/LR_train_and_test_on_exam_data.py --input_csv /scratchc/nrlab/wang04/ulyses_results_iteration/iteration_3_merge_below_3/lr_model/lr10/0.03-0.1_pairwise/lr_input.feat.cnv.tf.0.03-0.1_pairwise.csv
source ~/.bashrc;singularity exec         --bind /scratchc/nrlab/wang04/         --bind ~         --bind /home/nrlab         --bind /home/nrlab/wang04/ulyses/         --bind /scratchc/nrlab/wang04/ulyses         --bind /scratchc/nrlab/wang04/ulyses_results_iteration    /scratchc/nrlab/wang04/docker/tensorflow_gpu_cuda.sif python     /home/nrlab/wang04/ulyses/models_logistic_regression/LR_train_and_test_on_exam_data.py --input_csv /scratchc/nrlab/wang04/ulyses_results_iteration/iteration_3_merge_below_3/lr_model/lr10/0.1-1_pairwise/lr_input.feat.cnv.tf.0.1-1_pairwise.csv
source ~/.bashrc;singularity exec         --bind /scratchc/nrlab/wang04/         --bind ~         --bind /home/nrlab         --bind /home/nrlab/wang04/ulyses/         --bind /scratchc/nrlab/wang04/ulyses         --bind /scratchc/nrlab/wang04/ulyses_results_iteration    /scratchc/nrlab/wang04/docker/tensorflow_gpu_cuda.sif python     /home/nrlab/wang04/ulyses/models_logistic_regression/LR_train_and_test_on_exam_data.py --input_csv /scratchc/nrlab/wang04/ulyses_results_iteration/iteration_3_merge_below_3/lr_model/lr10/all/lr_input.feat.cnv.tf.all.csv 
