suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(tidymodels))
library(argparse)



###############################################################################
# parameters
###############################################################################


# use argparse to parse the parameters
parser <- argparse::ArgumentParser()
# add tf_label argument, default to 'all'
parser$add_argument("--tf_label", type = "character", help = "tf_label", default = "0-0.03_pairwise")
# add outdir argument, default as current directory
parser$add_argument("--outdir", type = "character", help = "outdir", default = ".")
# add model_data_file argument, default as "/home/nrlab/wang04/ulyses/xgboost/model_data.rda", this rda file is generated by /home/nrlab/wang04/ulyses/plot_mae/feature_viz_pre_filtering.R
parser$add_argument("--model_data_file", type = "character", help = "model_data_file", default = "/home/nrlab/wang04/ulyses/xgboost/xgboost_model_data.rds")
# add discard_chr19 argument, default as TRUE
parser$add_argument("--discard_chr19", type = "logical", help = "discard_chr19", default = FALSE)
# add remove_problematic_bin argument, default as TRUE
parser$add_argument("--remove_problematic_bin", type = "logical", help = "remove_problematic_bin", default = TRUE)

args <- parser$parse_args()
outdir <- args$outdir
model_data_file <- args$model_data_file
# load(model_data_file)
all_long_filter <- readRDS(model_data_file)
# source("/home/nrlab/wang04/ulyses/plot_mae/feature_viz_pre_filtering.R")
source("/home/nrlab/wang04/ulyses/models/cnn_xgboost_dataset_hyperparams.R")

tf_label <- args$tf_label
discard_chr19 <- args$discard_chr19
remove_problematic_bin <- args$remove_problematic_bin
rda_file <- file.path(outdir, paste0("xgboost_data", "_", tf_label, ".rda"))
independent_test_rda_file <- file.path(outdir, paste0("xgboost_data_independent_test", "_", tf_label, ".rda"))
###############################################################################
if (tf_label == 0.03) {
        tf_strat_vec <- c("Healthy", "[0, 0.03]")
} else if (tf_label == 0.1) {
        tf_strat_vec <- c("Healthy", "[0, 0.03]", "(0.03, 0.1]")
} else if (tf_label == 0.2) {
        tf_strat_vec <- c("Healthy", "[0, 0.03]", "(0.03, 0.1]", "(0.1, 0.2]")
} else if (tf_label == "all") {
        tf_strat_vec <- c("Healthy", "[0, 0.03]", "(0.03, 0.1]", "(0.1, 1]")
} else if (tf_label == "0-0.03_pairwise") {
        tf_strat_vec <- c("Healthy", "[0, 0.03]")
} else if (tf_label == "0.03-0.1_pairwise") {
        tf_strat_vec <- c("Healthy", "(0.03, 0.1]")
} else if (tf_label == "0.1-0.2_pairwise") {
        tf_strat_vec <- c("Healthy", "(0.1, 0.2]")
} else if (tf_label == "0.2-1_pairwise") {
        tf_strat_vec <- c("Healthy", "(0.2, 1]")
} else if (tf_label == "0.1-1_pairwise") {
        tf_strat_vec <- c("Healthy", "(0.1, 1]")
}

prepare_clean_input <- function(input, tf_strat_vec) {
        input_clean <- input %>%
                dplyr::filter(ichorcna_tf_strat %in% tf_strat_vec) %>%
                # dplyr::select(-c(primary, ichorcna_tf_strat, ichorcna_tf))
                dplyr::select(-c(ichorcna_tf_strat, ichorcna_tf))

        input_clean$bicohort <- factor(input_clean$bicohort, levels = c("Healthy", "Cancer"))

        return(input_clean)
}


# bin based feat selection

bin_feat_select <- function(feat, raw_tibble = all_long_filter) {
        all <- raw_tibble %>%
                dplyr::filter(assay == !!feat) %>%
                dplyr::select(bicohort, patient_id, ichorcna_tf, ichorcna_tf_strat, primary, rowname, value)

        ans <- all %>%
                dplyr::filter(rowname != "6p_6") %>%
                pivot_wider(names_from = rowname, values_from = value)

        return(ans)
}

size_feat_select <- function(feat, raw_tibble = all_long_filter, isize_range = paste("isize_", seq(isize_from_hyper, isize_to_hyper), sep = "")) {
        all <- raw_tibble %>%
                dplyr::filter(assay == !!feat) %>%
                dplyr::select(bicohort, patient_id, ichorcna_tf, ichorcna_tf_strat, primary, rowname, value)

        ans <- all %>%
                dplyr::filter(rowname %in% !!isize_range) %>%
                pivot_wider(names_from = rowname, values_from = value)

        return(ans)
}



# cnv_input <- bin_feat_select("cnv") %>%
#  prepare_clean_input(tf_strat_vec)

slRatio_input <- bin_feat_select("sl_ratio") %>%
        prepare_clean_input(tf_strat_vec)

ctRatio_input <- bin_feat_select("motif_ratio") %>%
        prepare_clean_input(tf_strat_vec)

length_input <- size_feat_select("length") %>%
        prepare_clean_input(tf_strat_vec)

sd_input <- size_feat_select("sd") %>%
        prepare_clean_input(tf_strat_vec)

#############################################################
# segment cnv
#############################################################

all_cnv <- all_long_filter %>%
        dplyr::filter(assay == "cnv") %>%
        dplyr::select(bicohort, patient_id, ichorcna_tf, ichorcna_tf_strat, primary, rowname, value)

cnv_input <- all_cnv %>%
        dplyr::filter(rowname != "6p_6") %>%
        dplyr::filter(ichorcna_tf_strat %in% tf_strat_vec) %>%
        dplyr::select(-c(ichorcna_tf, ichorcna_tf_strat)) %>%
        dplyr::mutate(chr = str_extract(rowname, "\\d+")) %>%
        group_by(primary, chr) %>%
        dplyr::mutate(pos = row_number()) %>%
        ungroup() %>%
        dplyr::group_by(primary)

cnv_input$rowname <- factor(cnv_input$rowname, levels = cnv_input$rowname %>% unique())

cnv_input_list <- group_split(cnv_input)
names(cnv_input_list) <- group_keys(cnv_input) %>% pull()



seg <- function(x) {
        bicohort <- x$bicohort
        patient_id <- x$patient_id
        rowname <- x$rowname
        primary <- x$primary
        log2ratio <- x$value

        CNA.object <- DNAcopy::CNA(
                genomdat = x$value,
                chrom = x$chr,
                maploc = x$pos,
                data.type = "logratio",
                sampleid = unique(x$primary),
                presorted = TRUE
        )

        smoothed.CNA.object <- DNAcopy::smooth.CNA(CNA.object)

        segment.smoothed.CNA.object <- DNAcopy::segment(smoothed.CNA.object,
                undo.splits = "sdundo",
                undo.SD = 3,
                verbose = 1
        )

        seg_num.mark <- segment.smoothed.CNA.object$output$num.mark
        seg_seg.mean <- segment.smoothed.CNA.object$output$seg.mean

        seg_value <- rep(seg_seg.mean, seg_num.mark)

        ans <- tibble(
                primary = primary,
                bicohort = bicohort,
                patient_id = patient_id,
                rowname = rowname,
                seg = seg_value,
                log2ratio = log2ratio
        )

        return(ans)
}




cnv_input_seg <- lapply(cnv_input_list, seg) %>%
        bind_rows()

cnv_input <- cnv_input_seg %>%
        select(-log2ratio) %>%
        pivot_wider(names_from = rowname, values_from = seg)
# select(-primary)

# IMPORTANT: the levels of bicohort affects how line 351 is set.
cnv_input$bicohort <- factor(cnv_input$bicohort, levels = c("Healthy", "Cancer"))

# shuffle the rows of cnv_input, make the order of patient_id the same as length_input$patient_id

order <- match(length_input$primary, cnv_input$primary)

cnv_input <- cnv_input[order, ]

# stop if cnv_input$paitent_id is not the same as length_input$patient_id
if (!all(cnv_input$primary == length_input$primary)) {
        stop("patient_id in cnv_input is not the same as length_input$patient_id")
}

##############################
# add prefix to column names
##############################

# add prefix of "cnv" to column names except for bicohort and patient_id
colnames_except <- c("bicohort", "patient_id", "primary")

cnv_input <- cnv_input %>%
        rename_with(~ paste0("cnv.", .), -all_of(colnames_except))

# add prefix of "slRatio" to column names except for bicohort and patient_id
slRatio_input <- slRatio_input %>%
        rename_with(~ paste0("slRatio.", .), -all_of(colnames_except))

# add prefix of "ctRatio" to column names except for bicohort and patient_id
ctRatio_input <- ctRatio_input %>%
        rename_with(~ paste0("ctRatio.", .), -all_of(colnames_except))

# add prefix of "length" to column names except for bicohort and patient_id
length_input <- length_input %>%
        rename_with(~ paste0("length.", .), -all_of(colnames_except))

# add prefix of "sd" to column names except for bicohort and patient_id
sd_input <- sd_input %>%
        rename_with(~ paste0("sd.", .), -all_of(colnames_except))


##############################
# remove a problematic bin/column, starts with "6p_6"
##############################



if (remove_problematic_bin && bin_size_hyper == "5mb") {
        cnv_input <- cnv_input %>%
                select(-starts_with("cnv.6p_6"))

        slRatio_input <- slRatio_input %>%
                select(-starts_with("slRatio.6p_6"))

        ctRatio_input <- ctRatio_input %>%
                select(-starts_with("ctRatio.6p_6"))
}



##############################
# filter chr19 in cnv, slRatio, ctRatio
##############################



if (discard_chr19) {
        cnv_input <- cnv_input %>%
                select(-starts_with("cnv.19"))

        slRatio_input <- slRatio_input %>%
                select(-starts_with("slRatio.19"))

        ctRatio_input <- ctRatio_input %>%
                select(-starts_with("ctRatio.19"))
}





##############################
# prepare the feature dataframe
##############################

# column bind cnv and sl_ratio
cnv_slRatio <- cnv_input %>%
        # bind the cnv_input and slRatio_input
        bind_cols(slRatio_input %>% select(-all_of(colnames_except)))

cnv_sd <- cnv_input %>%
        bind_cols(sd_input %>% select(-all_of(colnames_except)))

cnv_sd_length <- cnv_sd %>%
        bind_cols(length_input %>% select(-all_of(colnames_except)))

cnv_sd_length_ctRatio <- cnv_sd_length %>%
        bind_cols(ctRatio_input %>% select(-all_of(colnames_except)))

cnv_sd_length_ctRatio_slRatio <- cnv_sd_length_ctRatio %>%
        bind_cols(slRatio_input %>% select(-all_of(colnames_except)))

# new

length_sd <- length_input %>%
        bind_cols(sd_input %>% select(-all_of(colnames_except)))

length_cnv <- length_input %>%
        bind_cols(cnv_input %>% select(-all_of(colnames_except)))

length_ctRatio <- length_input %>%
        bind_cols(ctRatio_input %>% select(-all_of(colnames_except)))

length_slRatio <- length_input %>%
        bind_cols(slRatio_input %>% select(-all_of(colnames_except)))

cnv_ctRatio <- cnv_input %>%
        bind_cols(ctRatio_input %>% select(-all_of(colnames_except)))

slRatio_ctRatio <- slRatio_input %>%
        bind_cols(ctRatio_input %>% select(-all_of(colnames_except)))







feat_list <- list(
        "cnv" = cnv_input,
        "slRatio" = slRatio_input,
        "ctRatio" = ctRatio_input,
        "length" = length_input,
        "sd" = sd_input,
        "cnv_slRatio" = cnv_slRatio,
        "cnv_sd" = cnv_sd,
        "cnv_sd_length" = cnv_sd_length,
        "cnv_sd_length_ctRatio" = cnv_sd_length_ctRatio,
        "cnv_sd_length_ctRatio_slRatio" = cnv_sd_length_ctRatio_slRatio,
        "length_sd" = length_sd,
        "length_cnv" = length_cnv,
        "length_ctRatio" = length_ctRatio,
        "length_slRatio" = length_slRatio,
        "cnv_ctRatio" = cnv_ctRatio,
        "slRatio_ctRatio" = slRatio_ctRatio
)


##############################
# shuffle the rows, seed = seed_number_hyper
##############################

set.seed(seed_number_hyper)
shuffle_id <- sample(nrow(length_input))

shuffle_rows <- function(input, shuffle_id) {
        input[shuffle_id, ]
}

feat_list <- purrr::map(feat_list, shuffle_rows, shuffle_id)

# check if the patient_id columns of feat_list are the same
if (!all(map_lgl(feat_list, ~ all(feat_list[[1]]$primary == .x$primary)))) {
        stop("patient_id columns of feat_list are not the same")
}


##############################
# separate the samples in feat_list into train and test
##############################

load(final_test_hyper)

# make a functon to filter out the primary col in final_test_primary_vec
filter_out_primary <- function(input, test_primary_vec) {
        input %>%
                dplyr::filter(!input[["primary"]] %in% test_primary_vec)
}

# make a functon to keep the primary col in final_test_primary_vec
filter_in_primary <- function(input, test_primary_vec) {
        input %>%
                dplyr::filter(input[["primary"]] %in% test_primary_vec)
}


feat_list_train <- purrr::map(feat_list, filter_out_primary, test_primary_vec = final_test_primary_vec)
feat_list_test <- purrr::map(feat_list, filter_in_primary, test_primary_vec = final_test_primary_vec)






################################################################################
# export the train files
################################################################################

# save all to rda file
label_list <- names(feat_list_train) |> as.list()

save(feat_list_train, label_list, tf_label, file = rda_file)
message("Saved to ", rda_file)

# save each element to a separate csv file
for (i in seq_along(feat_list_train)) {
        csvdir <- file.path(outdir, tf_label)
        dir.create(csvdir, recursive = TRUE, showWarnings = FALSE)
        csvfile <- file.path(csvdir, paste0("xgboost_input", ".feat.", label_list[[i]], ".tf.", tf_label, ".csv"))
        write_csv(feat_list_train[[i]], csvfile)
        message("Saved to ", csvfile)
}

message("Train data done!")

################################################################################
# export the test files
################################################################################


# ##############################
# # shuffle the rows, seed = seed_number_hyper
# ##############################

# set.seed(seed_number_hyper)
# shuffle_id <- sample(nrow(feat_list_test$length))

# shuffle_rows <- function(input, shuffle_id) {
#         input[shuffle_id, ]
# }

# feat_list_test <- purrr::map(feat_list_test, shuffle_rows, shuffle_id)

# # check if the patient_id columns of feat_list_test are the same
# if (!all(map_lgl(feat_list_test, ~ all(feat_list_test[[1]]$primary == .x$primary)))) {
#         stop("patient_id columns of feat_list_test are not the same")
# }





################################################################################
# export the test files
################################################################################

# save all to rda file
label_list <- names(feat_list_test) |> as.list()

save(feat_list_test, label_list, tf_label, file = independent_test_rda_file)
message("Saved to ", independent_test_rda_file)

# save each element to a separate csv file
for (i in seq_along(feat_list_test)) {
        csvdir <- file.path(outdir, tf_label)
        dir.create(csvdir, recursive = TRUE, showWarnings = FALSE)
        csvfile <- file.path(csvdir, paste0("xgboost_input_independent_test", ".feat.", label_list[[i]], ".tf.", tf_label, ".csv"))
        write_csv(feat_list_test[[i]], csvfile)
        message("Saved to ", csvfile)
}


message("Test data done!")
